"""
Marks the GraphQL type as indexable entity.  Each type that should be an entity is required to be annotated with this directive.
"""
directive @entity on OBJECT

"""Defined a Subgraph ID for an object type"""
directive @subgraphId(id: String!) on OBJECT

"""
creates a virtual field on the entity that may be queried but cannot be set manually through the mappings API.
"""
directive @derivedFrom(field: String!) on FIELD_DEFINITION

"""
Indicates whether the current, partially filled bucket should be included in the response. Defaults to `exclude`
"""
enum Aggregation_current {
  """Exclude the current, partially filled bucket from the response"""
  exclude

  """Include the current, partially filled bucket in the response"""
  include
}

enum Aggregation_interval {
  hour
  day
}

scalar BigDecimal

scalar BigInt

input BlockChangedFilter {
  number_gte: Int!
}

input Block_height {
  hash: Bytes
  number: Int
  number_gte: Int
}

scalar Bytes

enum Chain {
  Arbitrum
  Gnosis
  Polygon
  Optimism
  Avalanche
  PolygonZkEvm
  Base
}

type Gauge {
  """ Equal to: <gaugeAddress>-<typeID> """
  id: ID!

  """ Address of the gauge """
  address: Bytes!

  """ Type of the gauge """
  type: GaugeType!

  """ Timestamp at which Balancer DAO added the gauge to GaugeController [seconds] 
  """
  addedTimestamp: Int!

  """ Reference to LiquidityGauge """
  liquidityGauge: LiquidityGauge

  """ Reference to RootGauge """
  rootGauge: RootGauge
}

type GaugeFactory {
  """ Factory contract address """
  id: ID!

  """ Number of gauges created through the factory """
  numGauges: Int!

  """ List of gauges created through the factory """
  gauges(skip: Int = 0, first: Int = 100, orderBy: LiquidityGauge_orderBy, orderDirection: OrderDirection, where: LiquidityGauge_filter): [LiquidityGauge!]
}

input GaugeFactory_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  numGauges: Int
  numGauges_not: Int
  numGauges_gt: Int
  numGauges_lt: Int
  numGauges_gte: Int
  numGauges_lte: Int
  numGauges_in: [Int!]
  numGauges_not_in: [Int!]
  gauges_: LiquidityGauge_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [GaugeFactory_filter]
  or: [GaugeFactory_filter]
}

enum GaugeFactory_orderBy {
  id
  numGauges
  gauges
}

type GaugeInjector {
  """ GaugeInjector contract address """
  id: ID!
}

input GaugeInjector_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [GaugeInjector_filter]
  or: [GaugeInjector_filter]
}

enum GaugeInjector_orderBy {
  id
}

type GaugeShare {
  """ Equal to: <userAddress>-<gaugeAddress> """
  id: ID!

  """ Reference to User entity """
  user: User!

  """ Reference to LiquidityGauge entity """
  gauge: LiquidityGauge!

  """ User's balance of gauge deposit tokens """
  balance: BigDecimal!
}

input GaugeShare_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  user: String
  user_not: String
  user_gt: String
  user_lt: String
  user_gte: String
  user_lte: String
  user_in: [String!]
  user_not_in: [String!]
  user_contains: String
  user_contains_nocase: String
  user_not_contains: String
  user_not_contains_nocase: String
  user_starts_with: String
  user_starts_with_nocase: String
  user_not_starts_with: String
  user_not_starts_with_nocase: String
  user_ends_with: String
  user_ends_with_nocase: String
  user_not_ends_with: String
  user_not_ends_with_nocase: String
  user_: User_filter
  gauge: String
  gauge_not: String
  gauge_gt: String
  gauge_lt: String
  gauge_gte: String
  gauge_lte: String
  gauge_in: [String!]
  gauge_not_in: [String!]
  gauge_contains: String
  gauge_contains_nocase: String
  gauge_not_contains: String
  gauge_not_contains_nocase: String
  gauge_starts_with: String
  gauge_starts_with_nocase: String
  gauge_not_starts_with: String
  gauge_not_starts_with_nocase: String
  gauge_ends_with: String
  gauge_ends_with_nocase: String
  gauge_not_ends_with: String
  gauge_not_ends_with_nocase: String
  gauge_: LiquidityGauge_filter
  balance: BigDecimal
  balance_not: BigDecimal
  balance_gt: BigDecimal
  balance_lt: BigDecimal
  balance_gte: BigDecimal
  balance_lte: BigDecimal
  balance_in: [BigDecimal!]
  balance_not_in: [BigDecimal!]

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [GaugeShare_filter]
  or: [GaugeShare_filter]
}

enum GaugeShare_orderBy {
  id
  user
  user__id
  gauge
  gauge__id
  gauge__symbol
  gauge__poolAddress
  gauge__poolId
  gauge__isKilled
  gauge__isPreferentialGauge
  gauge__relativeWeightCap
  gauge__streamer
  gauge__totalSupply
  balance
}

type GaugeType {
  """ Type ID """
  id: ID!

  """ Name of the type - empty string if call reverts """
  name: String!
}

input GaugeType_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  name: String
  name_not: String
  name_gt: String
  name_lt: String
  name_gte: String
  name_lte: String
  name_in: [String!]
  name_not_in: [String!]
  name_contains: String
  name_contains_nocase: String
  name_not_contains: String
  name_not_contains_nocase: String
  name_starts_with: String
  name_starts_with_nocase: String
  name_not_starts_with: String
  name_not_starts_with_nocase: String
  name_ends_with: String
  name_ends_with_nocase: String
  name_not_ends_with: String
  name_not_ends_with_nocase: String

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [GaugeType_filter]
  or: [GaugeType_filter]
}

enum GaugeType_orderBy {
  id
  name
}

type GaugeVote {
  """ Equal to: <userAddress>-<gaugeAddress> """
  id: ID!

  """ Reference to User entity """
  user: User!

  """ Reference to Gauge entity """
  gauge: Gauge!

  """ Weight of veBAL power user has used to vote """
  weight: BigDecimal

  """ Timestamp at which user voted [seconds] """
  timestamp: BigInt
}

input GaugeVote_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  user: String
  user_not: String
  user_gt: String
  user_lt: String
  user_gte: String
  user_lte: String
  user_in: [String!]
  user_not_in: [String!]
  user_contains: String
  user_contains_nocase: String
  user_not_contains: String
  user_not_contains_nocase: String
  user_starts_with: String
  user_starts_with_nocase: String
  user_not_starts_with: String
  user_not_starts_with_nocase: String
  user_ends_with: String
  user_ends_with_nocase: String
  user_not_ends_with: String
  user_not_ends_with_nocase: String
  user_: User_filter
  gauge: String
  gauge_not: String
  gauge_gt: String
  gauge_lt: String
  gauge_gte: String
  gauge_lte: String
  gauge_in: [String!]
  gauge_not_in: [String!]
  gauge_contains: String
  gauge_contains_nocase: String
  gauge_not_contains: String
  gauge_not_contains_nocase: String
  gauge_starts_with: String
  gauge_starts_with_nocase: String
  gauge_not_starts_with: String
  gauge_not_starts_with_nocase: String
  gauge_ends_with: String
  gauge_ends_with_nocase: String
  gauge_not_ends_with: String
  gauge_not_ends_with_nocase: String
  gauge_: Gauge_filter
  weight: BigDecimal
  weight_not: BigDecimal
  weight_gt: BigDecimal
  weight_lt: BigDecimal
  weight_gte: BigDecimal
  weight_lte: BigDecimal
  weight_in: [BigDecimal!]
  weight_not_in: [BigDecimal!]
  timestamp: BigInt
  timestamp_not: BigInt
  timestamp_gt: BigInt
  timestamp_lt: BigInt
  timestamp_gte: BigInt
  timestamp_lte: BigInt
  timestamp_in: [BigInt!]
  timestamp_not_in: [BigInt!]

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [GaugeVote_filter]
  or: [GaugeVote_filter]
}

enum GaugeVote_orderBy {
  id
  user
  user__id
  gauge
  gauge__id
  gauge__address
  gauge__addedTimestamp
  weight
  timestamp
}

input Gauge_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  address: Bytes
  address_not: Bytes
  address_gt: Bytes
  address_lt: Bytes
  address_gte: Bytes
  address_lte: Bytes
  address_in: [Bytes!]
  address_not_in: [Bytes!]
  address_contains: Bytes
  address_not_contains: Bytes
  type: String
  type_not: String
  type_gt: String
  type_lt: String
  type_gte: String
  type_lte: String
  type_in: [String!]
  type_not_in: [String!]
  type_contains: String
  type_contains_nocase: String
  type_not_contains: String
  type_not_contains_nocase: String
  type_starts_with: String
  type_starts_with_nocase: String
  type_not_starts_with: String
  type_not_starts_with_nocase: String
  type_ends_with: String
  type_ends_with_nocase: String
  type_not_ends_with: String
  type_not_ends_with_nocase: String
  type_: GaugeType_filter
  addedTimestamp: Int
  addedTimestamp_not: Int
  addedTimestamp_gt: Int
  addedTimestamp_lt: Int
  addedTimestamp_gte: Int
  addedTimestamp_lte: Int
  addedTimestamp_in: [Int!]
  addedTimestamp_not_in: [Int!]
  liquidityGauge: String
  liquidityGauge_not: String
  liquidityGauge_gt: String
  liquidityGauge_lt: String
  liquidityGauge_gte: String
  liquidityGauge_lte: String
  liquidityGauge_in: [String!]
  liquidityGauge_not_in: [String!]
  liquidityGauge_contains: String
  liquidityGauge_contains_nocase: String
  liquidityGauge_not_contains: String
  liquidityGauge_not_contains_nocase: String
  liquidityGauge_starts_with: String
  liquidityGauge_starts_with_nocase: String
  liquidityGauge_not_starts_with: String
  liquidityGauge_not_starts_with_nocase: String
  liquidityGauge_ends_with: String
  liquidityGauge_ends_with_nocase: String
  liquidityGauge_not_ends_with: String
  liquidityGauge_not_ends_with_nocase: String
  liquidityGauge_: LiquidityGauge_filter
  rootGauge: String
  rootGauge_not: String
  rootGauge_gt: String
  rootGauge_lt: String
  rootGauge_gte: String
  rootGauge_lte: String
  rootGauge_in: [String!]
  rootGauge_not_in: [String!]
  rootGauge_contains: String
  rootGauge_contains_nocase: String
  rootGauge_not_contains: String
  rootGauge_not_contains_nocase: String
  rootGauge_starts_with: String
  rootGauge_starts_with_nocase: String
  rootGauge_not_starts_with: String
  rootGauge_not_starts_with_nocase: String
  rootGauge_ends_with: String
  rootGauge_ends_with_nocase: String
  rootGauge_not_ends_with: String
  rootGauge_not_ends_with_nocase: String
  rootGauge_: RootGauge_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [Gauge_filter]
  or: [Gauge_filter]
}

enum Gauge_orderBy {
  id
  address
  type
  type__id
  type__name
  addedTimestamp
  liquidityGauge
  liquidityGauge__id
  liquidityGauge__symbol
  liquidityGauge__poolAddress
  liquidityGauge__poolId
  liquidityGauge__isKilled
  liquidityGauge__isPreferentialGauge
  liquidityGauge__relativeWeightCap
  liquidityGauge__streamer
  liquidityGauge__totalSupply
  rootGauge
  rootGauge__id
  rootGauge__chain
  rootGauge__recipient
  rootGauge__isKilled
  rootGauge__relativeWeightCap
}

"""8 bytes signed integer"""
scalar Int8

type LiquidityGauge {
  """ LiquidityGauge contract address """
  id: ID!

  """ ERC20 token symbol """
  symbol: String!

  """ Reference to Gauge entity - created when LiquidityGauge is added to GaugeController
  """
  gauge: Gauge

  """ Reference to Pool entity """
  pool: Pool

  """ Address of the pool (lp_token of the gauge) """
  poolAddress: Bytes!

  """ Pool ID if lp_token is a Balancer pool; null otherwise """
  poolId: Bytes

  """ Whether Balancer DAO killed the gauge """
  isKilled: Boolean!

  """ Whether the LiquidityGauge is the most recent added to GaugeController 
  """
  isPreferentialGauge: Boolean!

  """ Relative weight cap of the gauge (0.01 = 1%) - V2 factories only """
  relativeWeightCap: BigDecimal

  """ Address of the contract that streams reward tokens to the gauge - ChildChainLiquidityGauge only 
  """
  streamer: Bytes

  """ Factory contract address """
  factory: GaugeFactory!

  """ Total of BPTs users have staked in the LiquidityGauge """
  totalSupply: BigDecimal!

  """ List of reward tokens depositted in the gauge - ChildChainLiquidityGauge only 
  """
  rewardTokensList: [Bytes!]

  """ List of user shares """
  shares(skip: Int = 0, first: Int = 100, orderBy: GaugeShare_orderBy, orderDirection: OrderDirection, where: GaugeShare_filter): [GaugeShare!]

  """ List of reward tokens depositted in the gauge """
  tokens(skip: Int = 0, first: Int = 100, orderBy: RewardToken_orderBy, orderDirection: OrderDirection, where: RewardToken_filter): [RewardToken!]
}

input LiquidityGauge_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  symbol: String
  symbol_not: String
  symbol_gt: String
  symbol_lt: String
  symbol_gte: String
  symbol_lte: String
  symbol_in: [String!]
  symbol_not_in: [String!]
  symbol_contains: String
  symbol_contains_nocase: String
  symbol_not_contains: String
  symbol_not_contains_nocase: String
  symbol_starts_with: String
  symbol_starts_with_nocase: String
  symbol_not_starts_with: String
  symbol_not_starts_with_nocase: String
  symbol_ends_with: String
  symbol_ends_with_nocase: String
  symbol_not_ends_with: String
  symbol_not_ends_with_nocase: String
  gauge: String
  gauge_not: String
  gauge_gt: String
  gauge_lt: String
  gauge_gte: String
  gauge_lte: String
  gauge_in: [String!]
  gauge_not_in: [String!]
  gauge_contains: String
  gauge_contains_nocase: String
  gauge_not_contains: String
  gauge_not_contains_nocase: String
  gauge_starts_with: String
  gauge_starts_with_nocase: String
  gauge_not_starts_with: String
  gauge_not_starts_with_nocase: String
  gauge_ends_with: String
  gauge_ends_with_nocase: String
  gauge_not_ends_with: String
  gauge_not_ends_with_nocase: String
  gauge_: Gauge_filter
  pool: String
  pool_not: String
  pool_gt: String
  pool_lt: String
  pool_gte: String
  pool_lte: String
  pool_in: [String!]
  pool_not_in: [String!]
  pool_contains: String
  pool_contains_nocase: String
  pool_not_contains: String
  pool_not_contains_nocase: String
  pool_starts_with: String
  pool_starts_with_nocase: String
  pool_not_starts_with: String
  pool_not_starts_with_nocase: String
  pool_ends_with: String
  pool_ends_with_nocase: String
  pool_not_ends_with: String
  pool_not_ends_with_nocase: String
  pool_: Pool_filter
  poolAddress: Bytes
  poolAddress_not: Bytes
  poolAddress_gt: Bytes
  poolAddress_lt: Bytes
  poolAddress_gte: Bytes
  poolAddress_lte: Bytes
  poolAddress_in: [Bytes!]
  poolAddress_not_in: [Bytes!]
  poolAddress_contains: Bytes
  poolAddress_not_contains: Bytes
  poolId: Bytes
  poolId_not: Bytes
  poolId_gt: Bytes
  poolId_lt: Bytes
  poolId_gte: Bytes
  poolId_lte: Bytes
  poolId_in: [Bytes!]
  poolId_not_in: [Bytes!]
  poolId_contains: Bytes
  poolId_not_contains: Bytes
  isKilled: Boolean
  isKilled_not: Boolean
  isKilled_in: [Boolean!]
  isKilled_not_in: [Boolean!]
  isPreferentialGauge: Boolean
  isPreferentialGauge_not: Boolean
  isPreferentialGauge_in: [Boolean!]
  isPreferentialGauge_not_in: [Boolean!]
  relativeWeightCap: BigDecimal
  relativeWeightCap_not: BigDecimal
  relativeWeightCap_gt: BigDecimal
  relativeWeightCap_lt: BigDecimal
  relativeWeightCap_gte: BigDecimal
  relativeWeightCap_lte: BigDecimal
  relativeWeightCap_in: [BigDecimal!]
  relativeWeightCap_not_in: [BigDecimal!]
  streamer: Bytes
  streamer_not: Bytes
  streamer_gt: Bytes
  streamer_lt: Bytes
  streamer_gte: Bytes
  streamer_lte: Bytes
  streamer_in: [Bytes!]
  streamer_not_in: [Bytes!]
  streamer_contains: Bytes
  streamer_not_contains: Bytes
  factory: String
  factory_not: String
  factory_gt: String
  factory_lt: String
  factory_gte: String
  factory_lte: String
  factory_in: [String!]
  factory_not_in: [String!]
  factory_contains: String
  factory_contains_nocase: String
  factory_not_contains: String
  factory_not_contains_nocase: String
  factory_starts_with: String
  factory_starts_with_nocase: String
  factory_not_starts_with: String
  factory_not_starts_with_nocase: String
  factory_ends_with: String
  factory_ends_with_nocase: String
  factory_not_ends_with: String
  factory_not_ends_with_nocase: String
  factory_: GaugeFactory_filter
  totalSupply: BigDecimal
  totalSupply_not: BigDecimal
  totalSupply_gt: BigDecimal
  totalSupply_lt: BigDecimal
  totalSupply_gte: BigDecimal
  totalSupply_lte: BigDecimal
  totalSupply_in: [BigDecimal!]
  totalSupply_not_in: [BigDecimal!]
  rewardTokensList: [Bytes!]
  rewardTokensList_not: [Bytes!]
  rewardTokensList_contains: [Bytes!]
  rewardTokensList_not_contains: [Bytes!]
  shares_: GaugeShare_filter
  tokens_: RewardToken_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [LiquidityGauge_filter]
  or: [LiquidityGauge_filter]
}

enum LiquidityGauge_orderBy {
  id
  symbol
  gauge
  gauge__id
  gauge__address
  gauge__addedTimestamp
  pool
  pool__id
  pool__poolId
  pool__address
  poolAddress
  poolId
  isKilled
  isPreferentialGauge
  relativeWeightCap
  streamer
  factory
  factory__id
  factory__numGauges
  totalSupply
  rewardTokensList
  shares
  tokens
}

type LockSnapshot {
  """ Equal to <userAddress>-<timestamp> """
  id: ID!

  """ Reference to User entity """
  user: User!

  """ veBAL balance at the moment user locks """
  bias: BigDecimal!

  """ veBAL decay rate (per second) """
  slope: BigDecimal!

  """ Timestamp at which the snapshot was taken [seconds] """
  timestamp: Int!
}

input LockSnapshot_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  user: String
  user_not: String
  user_gt: String
  user_lt: String
  user_gte: String
  user_lte: String
  user_in: [String!]
  user_not_in: [String!]
  user_contains: String
  user_contains_nocase: String
  user_not_contains: String
  user_not_contains_nocase: String
  user_starts_with: String
  user_starts_with_nocase: String
  user_not_starts_with: String
  user_not_starts_with_nocase: String
  user_ends_with: String
  user_ends_with_nocase: String
  user_not_ends_with: String
  user_not_ends_with_nocase: String
  user_: User_filter
  bias: BigDecimal
  bias_not: BigDecimal
  bias_gt: BigDecimal
  bias_lt: BigDecimal
  bias_gte: BigDecimal
  bias_lte: BigDecimal
  bias_in: [BigDecimal!]
  bias_not_in: [BigDecimal!]
  slope: BigDecimal
  slope_not: BigDecimal
  slope_gt: BigDecimal
  slope_lt: BigDecimal
  slope_gte: BigDecimal
  slope_lte: BigDecimal
  slope_in: [BigDecimal!]
  slope_not_in: [BigDecimal!]
  timestamp: Int
  timestamp_not: Int
  timestamp_gt: Int
  timestamp_lt: Int
  timestamp_gte: Int
  timestamp_lte: Int
  timestamp_in: [Int!]
  timestamp_not_in: [Int!]

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [LockSnapshot_filter]
  or: [LockSnapshot_filter]
}

enum LockSnapshot_orderBy {
  id
  user
  user__id
  bias
  slope
  timestamp
}

type OmniVotingEscrowLock {
  """ Equal to: <userAdress>-<omniVotingEscrow> """
  id: ID!

  """ User on the local chain (reference to User entity) """
  localUser: User!

  """ User address on the remote chain """
  remoteUser: Bytes!

  """ Chain where the lock was bridged to """
  dstChainId: Int!

  """ veBAL balance at the moment user locks """
  bias: BigDecimal!

  """ veBAL decay rate (per second) """
  slope: BigDecimal!

  """ Timestamp the lock was created [seconds] """
  timestamp: Int!

  """ Reference to VotingEscrow entity """
  votingEscrowID: VotingEscrow!
}

input OmniVotingEscrowLock_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  localUser: String
  localUser_not: String
  localUser_gt: String
  localUser_lt: String
  localUser_gte: String
  localUser_lte: String
  localUser_in: [String!]
  localUser_not_in: [String!]
  localUser_contains: String
  localUser_contains_nocase: String
  localUser_not_contains: String
  localUser_not_contains_nocase: String
  localUser_starts_with: String
  localUser_starts_with_nocase: String
  localUser_not_starts_with: String
  localUser_not_starts_with_nocase: String
  localUser_ends_with: String
  localUser_ends_with_nocase: String
  localUser_not_ends_with: String
  localUser_not_ends_with_nocase: String
  localUser_: User_filter
  remoteUser: Bytes
  remoteUser_not: Bytes
  remoteUser_gt: Bytes
  remoteUser_lt: Bytes
  remoteUser_gte: Bytes
  remoteUser_lte: Bytes
  remoteUser_in: [Bytes!]
  remoteUser_not_in: [Bytes!]
  remoteUser_contains: Bytes
  remoteUser_not_contains: Bytes
  dstChainId: Int
  dstChainId_not: Int
  dstChainId_gt: Int
  dstChainId_lt: Int
  dstChainId_gte: Int
  dstChainId_lte: Int
  dstChainId_in: [Int!]
  dstChainId_not_in: [Int!]
  bias: BigDecimal
  bias_not: BigDecimal
  bias_gt: BigDecimal
  bias_lt: BigDecimal
  bias_gte: BigDecimal
  bias_lte: BigDecimal
  bias_in: [BigDecimal!]
  bias_not_in: [BigDecimal!]
  slope: BigDecimal
  slope_not: BigDecimal
  slope_gt: BigDecimal
  slope_lt: BigDecimal
  slope_gte: BigDecimal
  slope_lte: BigDecimal
  slope_in: [BigDecimal!]
  slope_not_in: [BigDecimal!]
  timestamp: Int
  timestamp_not: Int
  timestamp_gt: Int
  timestamp_lt: Int
  timestamp_gte: Int
  timestamp_lte: Int
  timestamp_in: [Int!]
  timestamp_not_in: [Int!]
  votingEscrowID: String
  votingEscrowID_not: String
  votingEscrowID_gt: String
  votingEscrowID_lt: String
  votingEscrowID_gte: String
  votingEscrowID_lte: String
  votingEscrowID_in: [String!]
  votingEscrowID_not_in: [String!]
  votingEscrowID_contains: String
  votingEscrowID_contains_nocase: String
  votingEscrowID_not_contains: String
  votingEscrowID_not_contains_nocase: String
  votingEscrowID_starts_with: String
  votingEscrowID_starts_with_nocase: String
  votingEscrowID_not_starts_with: String
  votingEscrowID_not_starts_with_nocase: String
  votingEscrowID_ends_with: String
  votingEscrowID_ends_with_nocase: String
  votingEscrowID_not_ends_with: String
  votingEscrowID_not_ends_with_nocase: String
  votingEscrowID_: VotingEscrow_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [OmniVotingEscrowLock_filter]
  or: [OmniVotingEscrowLock_filter]
}

enum OmniVotingEscrowLock_orderBy {
  id
  localUser
  localUser__id
  remoteUser
  dstChainId
  bias
  slope
  timestamp
  votingEscrowID
  votingEscrowID__id
  votingEscrowID__stakedSupply
}

"""Defines the order direction, either ascending or descending"""
enum OrderDirection {
  asc
  desc
}

type Pool {
  """ Address of the pool (lp_token of the gauge) """
  id: ID!

  """ Pool ID if lp_token is a Balancer pool; null otherwise """
  poolId: Bytes

  """ Address of the pool (lp_token of the gauge) """
  address: Bytes!

  """ Most recent, unkilled gauge in the GaugeController """
  preferentialGauge: LiquidityGauge

  """ List of the pool's gauges addresses """
  gaugesList: [Bytes!]!

  """ List of gauges created for the pool """
  gauges(skip: Int = 0, first: Int = 100, orderBy: LiquidityGauge_orderBy, orderDirection: OrderDirection, where: LiquidityGauge_filter): [LiquidityGauge!]
}

input Pool_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  poolId: Bytes
  poolId_not: Bytes
  poolId_gt: Bytes
  poolId_lt: Bytes
  poolId_gte: Bytes
  poolId_lte: Bytes
  poolId_in: [Bytes!]
  poolId_not_in: [Bytes!]
  poolId_contains: Bytes
  poolId_not_contains: Bytes
  address: Bytes
  address_not: Bytes
  address_gt: Bytes
  address_lt: Bytes
  address_gte: Bytes
  address_lte: Bytes
  address_in: [Bytes!]
  address_not_in: [Bytes!]
  address_contains: Bytes
  address_not_contains: Bytes
  preferentialGauge: String
  preferentialGauge_not: String
  preferentialGauge_gt: String
  preferentialGauge_lt: String
  preferentialGauge_gte: String
  preferentialGauge_lte: String
  preferentialGauge_in: [String!]
  preferentialGauge_not_in: [String!]
  preferentialGauge_contains: String
  preferentialGauge_contains_nocase: String
  preferentialGauge_not_contains: String
  preferentialGauge_not_contains_nocase: String
  preferentialGauge_starts_with: String
  preferentialGauge_starts_with_nocase: String
  preferentialGauge_not_starts_with: String
  preferentialGauge_not_starts_with_nocase: String
  preferentialGauge_ends_with: String
  preferentialGauge_ends_with_nocase: String
  preferentialGauge_not_ends_with: String
  preferentialGauge_not_ends_with_nocase: String
  preferentialGauge_: LiquidityGauge_filter
  gaugesList: [Bytes!]
  gaugesList_not: [Bytes!]
  gaugesList_contains: [Bytes!]
  gaugesList_not_contains: [Bytes!]
  gauges_: LiquidityGauge_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [Pool_filter]
  or: [Pool_filter]
}

enum Pool_orderBy {
  id
  poolId
  address
  preferentialGauge
  preferentialGauge__id
  preferentialGauge__symbol
  preferentialGauge__poolAddress
  preferentialGauge__poolId
  preferentialGauge__isKilled
  preferentialGauge__isPreferentialGauge
  preferentialGauge__relativeWeightCap
  preferentialGauge__streamer
  preferentialGauge__totalSupply
  gaugesList
  gauges
}

type Query {
  votingEscrow(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): VotingEscrow
  votingEscrows(
    skip: Int = 0
    first: Int = 100
    orderBy: VotingEscrow_orderBy
    orderDirection: OrderDirection
    where: VotingEscrow_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [VotingEscrow!]!
  omniVotingEscrowLock(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): OmniVotingEscrowLock
  omniVotingEscrowLocks(
    skip: Int = 0
    first: Int = 100
    orderBy: OmniVotingEscrowLock_orderBy
    orderDirection: OrderDirection
    where: OmniVotingEscrowLock_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [OmniVotingEscrowLock!]!
  votingEscrowLock(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): VotingEscrowLock
  votingEscrowLocks(
    skip: Int = 0
    first: Int = 100
    orderBy: VotingEscrowLock_orderBy
    orderDirection: OrderDirection
    where: VotingEscrowLock_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [VotingEscrowLock!]!
  lockSnapshot(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): LockSnapshot
  lockSnapshots(
    skip: Int = 0
    first: Int = 100
    orderBy: LockSnapshot_orderBy
    orderDirection: OrderDirection
    where: LockSnapshot_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [LockSnapshot!]!
  gaugeFactory(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): GaugeFactory
  gaugeFactories(
    skip: Int = 0
    first: Int = 100
    orderBy: GaugeFactory_orderBy
    orderDirection: OrderDirection
    where: GaugeFactory_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [GaugeFactory!]!
  liquidityGauge(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): LiquidityGauge
  liquidityGauges(
    skip: Int = 0
    first: Int = 100
    orderBy: LiquidityGauge_orderBy
    orderDirection: OrderDirection
    where: LiquidityGauge_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [LiquidityGauge!]!
  rootGauge(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): RootGauge
  rootGauges(
    skip: Int = 0
    first: Int = 100
    orderBy: RootGauge_orderBy
    orderDirection: OrderDirection
    where: RootGauge_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [RootGauge!]!
  singleRecipientGauge(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): SingleRecipientGauge
  singleRecipientGauges(
    skip: Int = 0
    first: Int = 100
    orderBy: SingleRecipientGauge_orderBy
    orderDirection: OrderDirection
    where: SingleRecipientGauge_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [SingleRecipientGauge!]!
  gauge(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): Gauge
  gauges(
    skip: Int = 0
    first: Int = 100
    orderBy: Gauge_orderBy
    orderDirection: OrderDirection
    where: Gauge_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [Gauge!]!
  pool(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): Pool
  pools(
    skip: Int = 0
    first: Int = 100
    orderBy: Pool_orderBy
    orderDirection: OrderDirection
    where: Pool_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [Pool!]!
  rewardToken(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): RewardToken
  rewardTokens(
    skip: Int = 0
    first: Int = 100
    orderBy: RewardToken_orderBy
    orderDirection: OrderDirection
    where: RewardToken_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [RewardToken!]!
  gaugeShare(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): GaugeShare
  gaugeShares(
    skip: Int = 0
    first: Int = 100
    orderBy: GaugeShare_orderBy
    orderDirection: OrderDirection
    where: GaugeShare_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [GaugeShare!]!
  gaugeType(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): GaugeType
  gaugeTypes(
    skip: Int = 0
    first: Int = 100
    orderBy: GaugeType_orderBy
    orderDirection: OrderDirection
    where: GaugeType_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [GaugeType!]!
  gaugeVote(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): GaugeVote
  gaugeVotes(
    skip: Int = 0
    first: Int = 100
    orderBy: GaugeVote_orderBy
    orderDirection: OrderDirection
    where: GaugeVote_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [GaugeVote!]!
  user(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): User
  users(
    skip: Int = 0
    first: Int = 100
    orderBy: User_orderBy
    orderDirection: OrderDirection
    where: User_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [User!]!
  gaugeInjector(
    id: ID!

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): GaugeInjector
  gaugeInjectors(
    skip: Int = 0
    first: Int = 100
    orderBy: GaugeInjector_orderBy
    orderDirection: OrderDirection
    where: GaugeInjector_filter

    """
    The block at which the query should be executed. Can either be a `{ hash: Bytes }` value containing a block hash, a `{ number: Int }` containing the block number, or a `{ number_gte: Int }` containing the minimum block number. In the case of `number_gte`, the query will be executed on the latest block only if the subgraph has progressed to or past the minimum block number. Defaults to the latest block when omitted.
    """
    block: Block_height

    """
    Set to `allow` to receive data even if the subgraph has skipped over errors while syncing.
    """
    subgraphError: _SubgraphErrorPolicy_! = deny
  ): [GaugeInjector!]!

  """Access to subgraph metadata"""
  _meta(block: Block_height): _Meta_
}

type RewardToken {
  """ Equal to: <tokenAddress>-<gaugeAddress> """
  id: ID!

  """ ERC20 token symbol - empty string if call to symbol() reverts """
  symbol: String!

  """ ERC20 token decimals - zero if call to decimals() reverts """
  decimals: Int!

  """ Reference to LiquidityGauge entity """
  gauge: LiquidityGauge!

  """ Rate of reward tokens streamed per second """
  rate: BigDecimal

  """ Timestamp at which finishes the period of rewards """
  periodFinish: BigInt

  """ Amount of reward tokens that has been deposited into the gauge """
  totalDeposited: BigDecimal!
}

input RewardToken_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  symbol: String
  symbol_not: String
  symbol_gt: String
  symbol_lt: String
  symbol_gte: String
  symbol_lte: String
  symbol_in: [String!]
  symbol_not_in: [String!]
  symbol_contains: String
  symbol_contains_nocase: String
  symbol_not_contains: String
  symbol_not_contains_nocase: String
  symbol_starts_with: String
  symbol_starts_with_nocase: String
  symbol_not_starts_with: String
  symbol_not_starts_with_nocase: String
  symbol_ends_with: String
  symbol_ends_with_nocase: String
  symbol_not_ends_with: String
  symbol_not_ends_with_nocase: String
  decimals: Int
  decimals_not: Int
  decimals_gt: Int
  decimals_lt: Int
  decimals_gte: Int
  decimals_lte: Int
  decimals_in: [Int!]
  decimals_not_in: [Int!]
  gauge: String
  gauge_not: String
  gauge_gt: String
  gauge_lt: String
  gauge_gte: String
  gauge_lte: String
  gauge_in: [String!]
  gauge_not_in: [String!]
  gauge_contains: String
  gauge_contains_nocase: String
  gauge_not_contains: String
  gauge_not_contains_nocase: String
  gauge_starts_with: String
  gauge_starts_with_nocase: String
  gauge_not_starts_with: String
  gauge_not_starts_with_nocase: String
  gauge_ends_with: String
  gauge_ends_with_nocase: String
  gauge_not_ends_with: String
  gauge_not_ends_with_nocase: String
  gauge_: LiquidityGauge_filter
  rate: BigDecimal
  rate_not: BigDecimal
  rate_gt: BigDecimal
  rate_lt: BigDecimal
  rate_gte: BigDecimal
  rate_lte: BigDecimal
  rate_in: [BigDecimal!]
  rate_not_in: [BigDecimal!]
  periodFinish: BigInt
  periodFinish_not: BigInt
  periodFinish_gt: BigInt
  periodFinish_lt: BigInt
  periodFinish_gte: BigInt
  periodFinish_lte: BigInt
  periodFinish_in: [BigInt!]
  periodFinish_not_in: [BigInt!]
  totalDeposited: BigDecimal
  totalDeposited_not: BigDecimal
  totalDeposited_gt: BigDecimal
  totalDeposited_lt: BigDecimal
  totalDeposited_gte: BigDecimal
  totalDeposited_lte: BigDecimal
  totalDeposited_in: [BigDecimal!]
  totalDeposited_not_in: [BigDecimal!]

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [RewardToken_filter]
  or: [RewardToken_filter]
}

enum RewardToken_orderBy {
  id
  symbol
  decimals
  gauge
  gauge__id
  gauge__symbol
  gauge__poolAddress
  gauge__poolId
  gauge__isKilled
  gauge__isPreferentialGauge
  gauge__relativeWeightCap
  gauge__streamer
  gauge__totalSupply
  rate
  periodFinish
  totalDeposited
}

type RootGauge {
  """ RootGauge contract address"""
  id: ID!

  """ Chain where emissions by this gauge will be bridged to """
  chain: Chain!

  """ Address where emissions by this gauge will be bridged to """
  recipient: Bytes!

  """ Reference to Gauge entity - created when LiquidityGauge is added to GaugeController
  """
  gauge: Gauge

  """ Whether Balancer DAO killed the gauge """
  isKilled: Boolean!

  """ Relative weight cap of the gauge (0.01 = 1%) - V2 factories only """
  relativeWeightCap: BigDecimal

  """ Factory contract address """
  factory: GaugeFactory!
}

input RootGauge_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  chain: Chain
  chain_not: Chain
  chain_in: [Chain!]
  chain_not_in: [Chain!]
  recipient: Bytes
  recipient_not: Bytes
  recipient_gt: Bytes
  recipient_lt: Bytes
  recipient_gte: Bytes
  recipient_lte: Bytes
  recipient_in: [Bytes!]
  recipient_not_in: [Bytes!]
  recipient_contains: Bytes
  recipient_not_contains: Bytes
  gauge: String
  gauge_not: String
  gauge_gt: String
  gauge_lt: String
  gauge_gte: String
  gauge_lte: String
  gauge_in: [String!]
  gauge_not_in: [String!]
  gauge_contains: String
  gauge_contains_nocase: String
  gauge_not_contains: String
  gauge_not_contains_nocase: String
  gauge_starts_with: String
  gauge_starts_with_nocase: String
  gauge_not_starts_with: String
  gauge_not_starts_with_nocase: String
  gauge_ends_with: String
  gauge_ends_with_nocase: String
  gauge_not_ends_with: String
  gauge_not_ends_with_nocase: String
  gauge_: Gauge_filter
  isKilled: Boolean
  isKilled_not: Boolean
  isKilled_in: [Boolean!]
  isKilled_not_in: [Boolean!]
  relativeWeightCap: BigDecimal
  relativeWeightCap_not: BigDecimal
  relativeWeightCap_gt: BigDecimal
  relativeWeightCap_lt: BigDecimal
  relativeWeightCap_gte: BigDecimal
  relativeWeightCap_lte: BigDecimal
  relativeWeightCap_in: [BigDecimal!]
  relativeWeightCap_not_in: [BigDecimal!]
  factory: String
  factory_not: String
  factory_gt: String
  factory_lt: String
  factory_gte: String
  factory_lte: String
  factory_in: [String!]
  factory_not_in: [String!]
  factory_contains: String
  factory_contains_nocase: String
  factory_not_contains: String
  factory_not_contains_nocase: String
  factory_starts_with: String
  factory_starts_with_nocase: String
  factory_not_starts_with: String
  factory_not_starts_with_nocase: String
  factory_ends_with: String
  factory_ends_with_nocase: String
  factory_not_ends_with: String
  factory_not_ends_with_nocase: String
  factory_: GaugeFactory_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [RootGauge_filter]
  or: [RootGauge_filter]
}

enum RootGauge_orderBy {
  id
  chain
  recipient
  gauge
  gauge__id
  gauge__address
  gauge__addedTimestamp
  isKilled
  relativeWeightCap
  factory
  factory__id
  factory__numGauges
}

type SingleRecipientGauge {
  """ SingleRecipientGauge contract address"""
  id: ID!

  """ Address where emissions for this gauge will be sent to """
  recipient: Bytes!

  """ Reference to Gauge entity - created when SingleRecipientGauge is added to GaugeController
  """
  gauge: Gauge

  """ Whether Balancer DAO killed the gauge """
  isKilled: Boolean!

  """ Relative weight cap of the gauge (0.01 = 1%) - V2 factories only """
  relativeWeightCap: BigDecimal

  """ Factory contract address """
  factory: GaugeFactory!
}

input SingleRecipientGauge_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  recipient: Bytes
  recipient_not: Bytes
  recipient_gt: Bytes
  recipient_lt: Bytes
  recipient_gte: Bytes
  recipient_lte: Bytes
  recipient_in: [Bytes!]
  recipient_not_in: [Bytes!]
  recipient_contains: Bytes
  recipient_not_contains: Bytes
  gauge: String
  gauge_not: String
  gauge_gt: String
  gauge_lt: String
  gauge_gte: String
  gauge_lte: String
  gauge_in: [String!]
  gauge_not_in: [String!]
  gauge_contains: String
  gauge_contains_nocase: String
  gauge_not_contains: String
  gauge_not_contains_nocase: String
  gauge_starts_with: String
  gauge_starts_with_nocase: String
  gauge_not_starts_with: String
  gauge_not_starts_with_nocase: String
  gauge_ends_with: String
  gauge_ends_with_nocase: String
  gauge_not_ends_with: String
  gauge_not_ends_with_nocase: String
  gauge_: Gauge_filter
  isKilled: Boolean
  isKilled_not: Boolean
  isKilled_in: [Boolean!]
  isKilled_not_in: [Boolean!]
  relativeWeightCap: BigDecimal
  relativeWeightCap_not: BigDecimal
  relativeWeightCap_gt: BigDecimal
  relativeWeightCap_lt: BigDecimal
  relativeWeightCap_gte: BigDecimal
  relativeWeightCap_lte: BigDecimal
  relativeWeightCap_in: [BigDecimal!]
  relativeWeightCap_not_in: [BigDecimal!]
  factory: String
  factory_not: String
  factory_gt: String
  factory_lt: String
  factory_gte: String
  factory_lte: String
  factory_in: [String!]
  factory_not_in: [String!]
  factory_contains: String
  factory_contains_nocase: String
  factory_not_contains: String
  factory_not_contains_nocase: String
  factory_starts_with: String
  factory_starts_with_nocase: String
  factory_not_starts_with: String
  factory_not_starts_with_nocase: String
  factory_ends_with: String
  factory_ends_with_nocase: String
  factory_not_ends_with: String
  factory_not_ends_with_nocase: String
  factory_: GaugeFactory_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [SingleRecipientGauge_filter]
  or: [SingleRecipientGauge_filter]
}

enum SingleRecipientGauge_orderBy {
  id
  recipient
  gauge
  gauge__id
  gauge__address
  gauge__addedTimestamp
  isKilled
  relativeWeightCap
  factory
  factory__id
  factory__numGauges
}

"""A string representation of microseconds UNIX timestamp (16 digits)"""
scalar Timestamp

type User {
  """ User address """
  id: ID!

  """ List of votes on gauges """
  gaugeVotes(skip: Int = 0, first: Int = 100, orderBy: GaugeVote_orderBy, orderDirection: OrderDirection, where: GaugeVote_filter): [GaugeVote!]

  """ List of gauge the user has shares """
  gaugeShares(skip: Int = 0, first: Int = 100, orderBy: GaugeShare_orderBy, orderDirection: OrderDirection, where: GaugeShare_filter): [GaugeShare!]

  """ List of locks the user created """
  votingLocks(skip: Int = 0, first: Int = 100, orderBy: VotingEscrowLock_orderBy, orderDirection: OrderDirection, where: VotingEscrowLock_filter): [VotingEscrowLock!]

  """ List of omni locks the user created """
  omniVotingLocks(skip: Int = 0, first: Int = 100, orderBy: OmniVotingEscrowLock_orderBy, orderDirection: OrderDirection, where: OmniVotingEscrowLock_filter): [OmniVotingEscrowLock!]
}

input User_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  gaugeVotes_: GaugeVote_filter
  gaugeShares_: GaugeShare_filter
  votingLocks_: VotingEscrowLock_filter
  omniVotingLocks_: OmniVotingEscrowLock_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [User_filter]
  or: [User_filter]
}

enum User_orderBy {
  id
  gaugeVotes
  gaugeShares
  votingLocks
  omniVotingLocks
}

type VotingEscrow {
  """ VotingEscrow contract address """
  id: ID!

  """ Amount of B-80BAL-20WETH BPT locked, only applies on mainnet """
  stakedSupply: BigDecimal

  """ List of veBAL locks created """
  locks(skip: Int = 0, first: Int = 100, orderBy: VotingEscrowLock_orderBy, orderDirection: OrderDirection, where: VotingEscrowLock_filter): [VotingEscrowLock!]

  """ List of veBAL locks created """
  omniLocks(skip: Int = 0, first: Int = 100, orderBy: OmniVotingEscrowLock_orderBy, orderDirection: OrderDirection, where: OmniVotingEscrowLock_filter): [OmniVotingEscrowLock!]
}

type VotingEscrowLock {
  """ Equal to: <userAdress>-<votingEscrow> """
  id: ID!

  """ Reference to User entity """
  user: User!

  """ veBAL balance at the moment user locks """
  bias: BigDecimal!

  """ veBAL decay rate (per second) """
  slope: BigDecimal!

  """ Timestamp at which the lock was created [seconds] """
  timestamp: Int!

  """ Timestamp at which B-80BAL-20WETH BPT can be unlocked by user [seconds] 
  """
  unlockTime: BigInt!

  """ Amount of B-80BAL-20WETH BPT the user has locked """
  lockedBalance: BigDecimal!

  """ Reference to VotingEscrow entity """
  votingEscrowID: VotingEscrow!

  """ Timestamp at which the lcok was created [seconds]. Same as timestamp """
  updatedAt: Int!
}

input VotingEscrowLock_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  user: String
  user_not: String
  user_gt: String
  user_lt: String
  user_gte: String
  user_lte: String
  user_in: [String!]
  user_not_in: [String!]
  user_contains: String
  user_contains_nocase: String
  user_not_contains: String
  user_not_contains_nocase: String
  user_starts_with: String
  user_starts_with_nocase: String
  user_not_starts_with: String
  user_not_starts_with_nocase: String
  user_ends_with: String
  user_ends_with_nocase: String
  user_not_ends_with: String
  user_not_ends_with_nocase: String
  user_: User_filter
  bias: BigDecimal
  bias_not: BigDecimal
  bias_gt: BigDecimal
  bias_lt: BigDecimal
  bias_gte: BigDecimal
  bias_lte: BigDecimal
  bias_in: [BigDecimal!]
  bias_not_in: [BigDecimal!]
  slope: BigDecimal
  slope_not: BigDecimal
  slope_gt: BigDecimal
  slope_lt: BigDecimal
  slope_gte: BigDecimal
  slope_lte: BigDecimal
  slope_in: [BigDecimal!]
  slope_not_in: [BigDecimal!]
  timestamp: Int
  timestamp_not: Int
  timestamp_gt: Int
  timestamp_lt: Int
  timestamp_gte: Int
  timestamp_lte: Int
  timestamp_in: [Int!]
  timestamp_not_in: [Int!]
  unlockTime: BigInt
  unlockTime_not: BigInt
  unlockTime_gt: BigInt
  unlockTime_lt: BigInt
  unlockTime_gte: BigInt
  unlockTime_lte: BigInt
  unlockTime_in: [BigInt!]
  unlockTime_not_in: [BigInt!]
  lockedBalance: BigDecimal
  lockedBalance_not: BigDecimal
  lockedBalance_gt: BigDecimal
  lockedBalance_lt: BigDecimal
  lockedBalance_gte: BigDecimal
  lockedBalance_lte: BigDecimal
  lockedBalance_in: [BigDecimal!]
  lockedBalance_not_in: [BigDecimal!]
  votingEscrowID: String
  votingEscrowID_not: String
  votingEscrowID_gt: String
  votingEscrowID_lt: String
  votingEscrowID_gte: String
  votingEscrowID_lte: String
  votingEscrowID_in: [String!]
  votingEscrowID_not_in: [String!]
  votingEscrowID_contains: String
  votingEscrowID_contains_nocase: String
  votingEscrowID_not_contains: String
  votingEscrowID_not_contains_nocase: String
  votingEscrowID_starts_with: String
  votingEscrowID_starts_with_nocase: String
  votingEscrowID_not_starts_with: String
  votingEscrowID_not_starts_with_nocase: String
  votingEscrowID_ends_with: String
  votingEscrowID_ends_with_nocase: String
  votingEscrowID_not_ends_with: String
  votingEscrowID_not_ends_with_nocase: String
  votingEscrowID_: VotingEscrow_filter
  updatedAt: Int
  updatedAt_not: Int
  updatedAt_gt: Int
  updatedAt_lt: Int
  updatedAt_gte: Int
  updatedAt_lte: Int
  updatedAt_in: [Int!]
  updatedAt_not_in: [Int!]

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [VotingEscrowLock_filter]
  or: [VotingEscrowLock_filter]
}

enum VotingEscrowLock_orderBy {
  id
  user
  user__id
  bias
  slope
  timestamp
  unlockTime
  lockedBalance
  votingEscrowID
  votingEscrowID__id
  votingEscrowID__stakedSupply
  updatedAt
}

input VotingEscrow_filter {
  id: ID
  id_not: ID
  id_gt: ID
  id_lt: ID
  id_gte: ID
  id_lte: ID
  id_in: [ID!]
  id_not_in: [ID!]
  stakedSupply: BigDecimal
  stakedSupply_not: BigDecimal
  stakedSupply_gt: BigDecimal
  stakedSupply_lt: BigDecimal
  stakedSupply_gte: BigDecimal
  stakedSupply_lte: BigDecimal
  stakedSupply_in: [BigDecimal!]
  stakedSupply_not_in: [BigDecimal!]
  locks_: VotingEscrowLock_filter
  omniLocks_: OmniVotingEscrowLock_filter

  """Filter for the block changed event."""
  _change_block: BlockChangedFilter
  and: [VotingEscrow_filter]
  or: [VotingEscrow_filter]
}

enum VotingEscrow_orderBy {
  id
  stakedSupply
  locks
  omniLocks
}

type _Block_ {
  """The hash of the block"""
  hash: Bytes

  """The block number"""
  number: Int!

  """Integer representation of the timestamp stored in blocks for the chain"""
  timestamp: Int

  """The hash of the parent block"""
  parentHash: Bytes
}

"""The type for the top-level _meta field"""
type _Meta_ {
  """
  Information about a specific subgraph block. The hash of the block
  will be null if the _meta field has a block constraint that asks for
  a block number. It will be filled if the _meta field has no block constraint
  and therefore asks for the latest  block
  """
  block: _Block_!

  """The deployment ID"""
  deployment: String!

  """If `true`, the subgraph encountered indexing errors at some past block"""
  hasIndexingErrors: Boolean!
}

enum _SubgraphErrorPolicy_ {
  """Data will be returned even if the subgraph has indexing errors"""
  allow

  """
  If the subgraph has indexing errors, data will be omitted. The default.
  """
  deny
}